services:
  - type: web
    name: nakaYoshiTube
    env: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /watch
        destination: /index.html
      - type: rewrite
        source: /shorts/*
        destination: /index.html
      - type: rewrite
        source: /search
        destination: /index.html
      - type: rewrite
        source: /channel/*
        destination: /index.html
      - type: rewrite
        source: /feed/*
        destination: /index.html
      - type: rewrite
        source: /settings
        destination: /index.html
      - type: rewrite
        source: /setting
        destination: /index.html
      - type: rewrite
        source: /home
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html